# Generated by Django 5.2.6 on 2025-09-30 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.CharField(blank=True, null=True, verbose_name='Bio'),
        ),
    ]
