# Generated by Django 5.2.6 on 2025-09-30 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_alter_profile_bio'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
