# Generated by Django 5.2.6 on 2025-09-20 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_alter_profile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='display_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile/'),
        ),
    ]
